// Code generated by ogen, DO NOT EDIT.

package api

import "github.com/ogen-go/ogen/validate"

// Equal compares two ConditionGroup instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a ConditionGroup) Equal(b ConditionGroup, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "ConditionGroup",
		})
	}

	// Compare optional field: Operator
	if a.Operator.Set != b.Operator.Set {
		return false
	}
	if a.Operator.Set {
		if a.Operator.Value != b.Operator.Value {
			return false
		}
	}
	// Compare optional field: Condition
	if a.Condition.Set != b.Condition.Set {
		return false
	}
	if a.Condition.Set {
		if !a.Condition.Value.Equal(b.Condition.Value, depth+1) {
			return false
		}
	}
	return true
}
