version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    groups:
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
