// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// SendMessage implements sendMessage operation.
//
// POST /messages
func (UnimplementedHandler) SendMessage(ctx context.Context, req Message) error {
	return ht.ErrNotImplemented
}
