openapi: 3.0.3
info:
  title: title
  version: v0.1.0
paths:
  /foo:
    get:
      operationId: getFoo
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringEnumWithNumber'
components:
  schemas:
    StringEnumWithNumber:
      type: string
      enum: ["wasd", 2, true]
