openapi: 3.0.3
info:
  title: API
  version: 0.1.0
paths:
  /optional:
    get:
      operationId: optional
      parameters:
        - name: date
          in: query
          schema:
            type: string
            format: date
            x-ogen-time-format: 02/01/2006
            default: 04/03/2001
        - name: time
          in: query
          schema:
            type: string
            format: time
            x-ogen-time-format: 3:04PM
            default: 1:23AM
        - name: dateTime
          in: query
          schema:
            type: string
            format: date-time
            x-ogen-time-format: 2006-01-02T15:04:05.999999999Z07:00
            default: 2001-03-04T01:23:45.123456789-07:00
        - name: alias
          in: query
          schema:
            $ref: '#/components/schemas/Alias'
            default: 04/03/2001 01:23:45AM
      responses:
        '200':
          description: Test
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    format: date
                    x-ogen-time-format: 02/01/2006
                    default: 04/03/2001
                  time:
                    type: string
                    format: time
                    x-ogen-time-format: 3:04PM
                    default: 1:23AM
                  dateTime:
                    type: string
                    format: date-time
                    x-ogen-time-format: 2006-01-02T15:04:05.999999999Z07:00
                    default: 2001-03-04T01:23:45.123456789-07:00
                  alias:
                    $ref: '#/components/schemas/Alias'
                    default: 04/03/2001 01:23:45AM
  /required:
    get:
      operationId: required
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
            x-ogen-time-format: 02/01/2006
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
            x-ogen-time-format: 3:04PM
        - name: dateTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
            x-ogen-time-format: 2006-01-02T15:04:05.999999999Z07:00
        - name: alias
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Alias'
      responses:
        '200':
          description: Test
          content:
            application/json:
              schema:
                type: object
                required:
                  - date
                  - time
                  - dateTime
                  - alias
                properties:
                  date:
                    type: string
                    format: date
                    x-ogen-time-format: 02/01/2006
                  time:
                    type: string
                    format: time
                    x-ogen-time-format: 3:04PM
                  dateTime:
                    type: string
                    format: date
                    x-ogen-time-format: 2006-01-02T15:04:05.999999999Z07:00
                  alias:
                    $ref: '#/components/schemas/Alias'
components:
  schemas:
    Alias:
      type: string
      format: date-time
      x-ogen-time-format: 02/01/2006 3:04:05PM
