// Code generated by ogen, DO NOT EDIT.
package api

type GetMixedDataRes interface {
	getMixedDataRes()
}

type GetRawDataInsideOperationGroupRes interface {
	getRawDataInsideOperationGroupRes()
}

type GetRawDataRes interface {
	getRawDataRes()
}
