// Code generated by ogen, DO NOT EDIT.

package api

// SetFake set fake values.
func (s *AllRequestBodiesApplicationJSON) SetFake() {
	var unwrapped SimpleObject
	{
		unwrapped.SetFake()
	}
	*s = AllRequestBodiesApplicationJSON(unwrapped)
}

// SetFake set fake values.
func (s *AllRequestBodiesApplicationXWwwFormUrlencoded) SetFake() {
	var unwrapped SimpleObject
	{
		unwrapped.SetFake()
	}
	*s = AllRequestBodiesApplicationXWwwFormUrlencoded(unwrapped)
}

// SetFake set fake values.
func (s *AllRequestBodiesMultipartFormData) SetFake() {
	var unwrapped SimpleObject
	{
		unwrapped.SetFake()
	}
	*s = AllRequestBodiesMultipartFormData(unwrapped)
}

// SetFake set fake values.
func (s *AllRequestBodiesOptionalApplicationJSON) SetFake() {
	var unwrapped OptSimpleObject
	{
		unwrapped.SetFake()
	}
	*s = AllRequestBodiesOptionalApplicationJSON(unwrapped)
}

// SetFake set fake values.
func (s *AllRequestBodiesOptionalApplicationXWwwFormUrlencoded) SetFake() {
	var unwrapped OptSimpleObject
	{
		unwrapped.SetFake()
	}
	*s = AllRequestBodiesOptionalApplicationXWwwFormUrlencoded(unwrapped)
}

// SetFake set fake values.
func (s *AllRequestBodiesOptionalMultipartFormData) SetFake() {
	var unwrapped OptSimpleObject
	{
		unwrapped.SetFake()
	}
	*s = AllRequestBodiesOptionalMultipartFormData(unwrapped)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptSimpleObject) SetFake() {
	var elem SimpleObject
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *SimpleObject) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Age.SetFake()
		}
	}
}
