// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	FooBarBazGetOperation   OperationName = "FooBarBazGet"
	FooBarQuxGetOperation   OperationName = "FooBarQuxGet"
	FooParamXyzGetOperation OperationName = "FooParamXyzGet"
)
