name: Autocommit `go mod tidy`

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
    inputs:
      repository:
        type: string
        required: true
      ref:
        type: string
        required: true

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: false

      # Notice: we're using read-only cache.
      #
      # See https://github.com/actions/setup-go/issues/357#issuecomment-1486486358
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-go-

      - name: Tidy go.mod files
        run: make tidy tidy_examples

        # See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#allowing-dependabot-to-rebase-and-force-push-over-extra-commits
        # that is why we add `[dependabot skip]` to commit.
      - name: Commit and push
        if: github.event.pull_request.user.login == 'dependabot[bot]' && failure() && steps.git-diff.outcome != 'success'
        run: |
          git add go.mod go.sum
          git add examples/go.mod examples/go.sum

          git \
            -c user.name="GitHub" \
            -c user.email="actions@github.com" \
            commit \
            -m "chore: go mod tidy" \
            -m "[dependabot skip]" \
            --author="GitHub"

          git push origin
